[package]
name = "simple-rust-database"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
rustyline = "15.0.0"
sqlparser = "0.55.0"
lazy_static = "1.4.0"
bincode = { version = "2.0.0", features = ["derive", "std"] }
